name: "composite-private"

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: "ubuntu-latest"
    steps:
      - run: "pwd"
      - uses: "actions/checkout@v2"
      - run: "pwd"
      - uses: "actions/checkout@v2"
        with:
          repository: "mythrnr/workspace"
          token: "${{ secrets.SECRET_TOKEN }}"
          path: "../../"
      - run: "pwd"
      - uses: "./../../.github/actions/private-example"
