name: "composite-example"

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "./.github/actions/composite-example"
      # - uses: "mythrnr/actions-example/.github/actions/composite-example@master"
