name: "composite-private"

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/checkout@v2"
        with:
          repository: "mythrnr/actions-private-example"
          token: "${{ secrets.SECRET_TOKEN }}"
          path: "./.github/actions/private-example"

      - uses: "./.github/actions/private-example"
