name: "matrix_array"

on:
  workflow_dispatch:
    inputs:
      target:
        description: "sample input (1 | 2 | 3)"
        required: true
        default: ""

jobs:
  debug_array:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        entries:
          - { key: 1, value: "value1" }
          - { key: 2, value: "value2" }
          - { key: 2, value: "value3" }
          - { key: 3, value: "value4" }
          - { key: 3, value: "value5" }
          - { key: 3, value: "value6" }

    env:
      RUN: "${{ matrix.entries.key == github.event.inputs.target }}"

    steps:
      # - if: "matrix.entries.key == github.event.inputs.target"
      #   name: "Set job as run"
      #   run: echo "RUN=1" >> $GITHUB_ENV

      - if: "env.RUN"
        run: "echo ${{ matrix.entries.value }}"
