name: "matrix_array"

on:
  workflow_dispatch:
    inputs:
      target:
        description: "sample input (1 | 2 | 3)"
        required: true
        default: ""

jobs:
  debug_include:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        values:
          - { target: 1, value: "value1" }
          - { target: 2, value: "value2" }
          - { target: 2, value: "value3" }
          - { target: 3, value: "value3" }
          - { target: 3, value: "value4" }
          - { target: 3, value: "value6" }
    steps:
      - if: "matrix.values.target == github.event.inputs.target"
        run: "echo ${{ matrix.values.value }}"
